/* Generated by tex3ds */
#pragma once

#define icons_prev_sng_idx 0
#define icons_next_sng_idx 1
#define icons_back_chevron_idx 2
#define icons_batt_1_idx 3
#define icons_batt_2_idx 4
#define icons_batt_3_idx 5
#define icons_batt_4_idx 6
#define icons_batt_5_idx 7
#define icons_batt_6_idx 8
#define icons_batt_full_idx 9
#define icons_playing_idx 10
#define icons_paused_idx 11
#define icons_wifi_min_idx 12
#define icons_wifi_med_idx 13
#define icons_wifi_full_idx 14
#define icons_loop_one_idx 15
#define icons_loop_off_idx 16
#define icons_shuffle_on_idx 17
#define icons_shuffle_off_idx 18
#define icons_loop_all_idx 19
